### PR TITLE
add request options object to each response

### PR DESCRIPTION
**Pull request by whitecolor**
add corresponding request options object to each response

### CODE REVIEW

**Comment by whitecolor** [comment]
Well will add docs in next commit if it is ok.

**Comment by whitecolor** [comment]
Maybe if this can be accomplished quite easy there is no need to add this to driver.

**Comment by whitecolor** [comment]
Just realized that you driver returns stream of streams of responses to get rid of attaching request options to each response.. well I wanted to distinct responses "within request", but maybe that goes against current driver concept.

**Comment by staltz** [comment]
Merged. Thanks!

**Pull request merged**
